[package]
name = "rdb"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "2.1.0"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = "1.0.133"
semver = "1.0.4"
unicode-segmentation = "1.8.0"
lazy_static = "1.4.0"
regex = "1.5.4"
